title: Fundación Planeta Azul Caribe (FUPAC) - planetaazulcaribe.org
author: Planeta Azul Caribe
iam: Planeta Azul Caribe
email: fundacionplanetaazul@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenidos a la página web de Planeta Azul Caribe.
keywords: planeta,azul,caribe,ong
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://planetaazulcaribe.org" # the base hostname & protocol for your site, e.g. http://example.com

twitter_url: https://twitter.com/planetaazulcaribe
github_url:
facebook_url: https://www.facebook.com/fupaccartagena
linkedin_url: https://www.linkedin.com
instagram_url:

# Tracker
analytics: UA-65020023-1 # Google Analytics

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "blog/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
